version: '3'

includes:
  app_ddash_tasks:
    taskfile: ./taskfiles/apps/ddash.yml
    flatten: true
  app_github_ingestor_tasks:
    taskfile: ./taskfiles/apps/githubappingestor.yml
    flatten: true
  app_gitlab_ingestor_tasks:
    taskfile: ./taskfiles/apps/gitlabingestor.yml
    flatten: true
  app_webhookgenerator_tasks:
    taskfile: ./taskfiles/apps/webhookgenerator.yml
    flatten: true
  app_eventpublisher_tasks:
    taskfile: ./taskfiles/apps/eventpublisher.yml
    flatten: true
  app_eventbackfill_tasks:
    taskfile: ./taskfiles/apps/eventbackfill.yml
    flatten: true
  app_dbshape_tasks:
    taskfile: ./taskfiles/apps/dbshape.yml
    flatten: true
  app_projectionsync_tasks:
    taskfile: ./taskfiles/apps/projectionsync.yml
    flatten: true
  events_tasks:
    taskfile: ./taskfiles/events.yml
    flatten: true
  loadtest_tasks:
    taskfile: ./taskfiles/loadtest.yml
    flatten: true
  e2e_tasks:
    taskfile: ./taskfiles/e2e.yml
    flatten: true
  mvp_tasks:
    taskfile: ./taskfiles/mvp.yml
    flatten: true
  remote_tasks:
    taskfile: ./taskfiles/remote.yml
    flatten: true
  deploy_tasks:
    taskfile: ./taskfiles/deploy.yml
    flatten: true
  quality_tasks:
    taskfile: ./taskfiles/quality.yml
    flatten: true
  package_tasks:
    taskfile: ./taskfiles/package.yml
    flatten: true
