// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"strings"
)

type Status string

type Service struct {
	Title           string
	Description     string
	Footer          string
	Context         string
	Environment     string
	Team            string
	Status          Status
	LastDeploy      string
	DeployDuration  string
	Revision        string
	CommitSHA       string
	CommitURL       string
	CommitIndex     int
	RepoURL         string
	LogsURL         string
	Endpoint        string
	ActionLabel     string
	ActionKind      string
	ActionDisabled  bool
	MissingMetadata int
	MetadataTags    string
}

type MetadataFilterOption struct {
	Value string
	Label string
}

type ServiceLink struct {
	Label string
	URL   string
}

type ServiceField struct {
	Label      string
	Value      string
	Filterable bool
}

type ServiceEnvironment struct {
	Name            string
	LastDeploy      string
	LastDeployedAgo string
	DeployedRef     string
	CommitURL       string
	DeployCount7d   int
	DeployCount30d  int
	DailyRate30d    string
}

type GitCommit struct {
	SHA     string
	Message string
	URL     string
}

type DeploymentRecord struct {
	Ref         string
	PreviousRef string
	ChangeLog   string
	Commits     int
	DeployedAt  string
	DeployedAgo string
	ReleaseURL  string
	Environment string
}

type ServiceRiskEvent struct {
	When          string
	Environment   string
	Artifact      string
	ChainID       string
	PipelineRunID string
	RunURL        string
	ActorName     string
}

type GitHubInstallationMapping struct {
	InstallationID     int64
	OrganizationLabel  string
	Endpoint           string
	DefaultEnvironment string
	Status             string
}

type DeploymentStatus string

type DeploymentRow struct {
	Service      string
	Environment  string
	DeployedAt   string
	Status       DeploymentStatus
	JobURL       string
	MetadataTags string
}

type ServiceDetail struct {
	Title             string
	Description       string
	Context           string
	Team              string
	IntegrationType   string
	MissingMetadata   int
	MetadataSaveURL   string
	MetadataFields    []ServiceField
	CustomFields      []ServiceField
	OrgRequiredFields []ServiceField
	Environments      []ServiceEnvironment
	PendingCommits    []GitCommit
	DeploymentHistory []DeploymentRecord
	LastStatus        string
	DriftCount        int
	FailedStreak      int
	Success30d        int
	Failures30d       int
	Rollbacks30d      int
	ChangeFailureRate string
	RiskEvents        []ServiceRiskEvent
	Dependencies      []string
	Dependants        []string
	AvailableServices []string
}

type StatusOption struct {
	Value Status
	Label string
}

type EnvironmentOption struct {
	Value string
	Label string
}

type ServiceGroup struct {
	Name     string
	Status   Status
	Services []Service
}

const (
	StatusAll         Status = "all"
	StatusSynced      Status = "synced"
	StatusProgressing Status = "progressing"
	StatusOutOfSync   Status = "out-of-sync"
	StatusWarning     Status = "warning"
	StatusUnknown     Status = "unknown"
)

const (
	DeploymentQueued     DeploymentStatus = "queued"
	DeploymentProcessing DeploymentStatus = "processing"
	DeploymentSuccess    DeploymentStatus = "success"
	DeploymentError      DeploymentStatus = "error"
)

type statusTheme struct {
	Accent     string
	PillBg     string
	PillBorder string
	PillText   string
	Label      string
}

func DefaultStatusOptions() []StatusOption {
	return []StatusOption{
		{Value: StatusAll, Label: "All statuses"},
		{Value: StatusSynced, Label: "Synced"},
		{Value: StatusProgressing, Label: "Progressing"},
		{Value: StatusOutOfSync, Label: "Out of sync"},
		{Value: StatusWarning, Label: "Warning"},
		{Value: StatusUnknown, Label: "Unknown"},
	}
}

func RequiredFieldsJSON(fields []ServiceField) string {
	parts := make([]string, 0, len(fields))
	for _, field := range fields {
		parts = append(parts, fmt.Sprintf(`{"label":%q,"type":%q,"filterable":%t}`, field.Label, field.Value, field.Filterable))
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ","))
}

func StringListJSON(values []string) string {
	parts := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" {
			continue
		}
		parts = append(parts, fmt.Sprintf("%q", value))
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ","))
}

func ServiceFieldsJSON(fields []ServiceField) string {
	parts := make([]string, 0, len(fields))
	for _, field := range fields {
		parts = append(parts, fmt.Sprintf(`{"label":%q,"value":%q}`, field.Label, field.Value))
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ","))
}

func ComponentsNoop() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<span class=\"hidden\"></span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
