// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Commit struct {
	ID          int64
	ServiceID   int64
	Sha         string
	Message     string
	Url         sql.NullString
	CommittedAt string
}

type Deployment struct {
	ID            int64
	ServiceID     int64
	EnvironmentID int64
	DeployedAt    string
	Status        string
	JobUrl        sql.NullString
	ReleaseRef    sql.NullString
	ReleaseUrl    sql.NullString
	CommitCount   sql.NullInt64
	CreatedAt     sql.NullTime
}

type Environment struct {
	ID   int64
	Name string
}

type Organization struct {
	ID            int64
	Name          string
	AuthToken     string
	WebhookSecret string
	Enabled       int64
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type OrganizationRequiredField struct {
	ID             int64
	OrganizationID int64
	Label          string
	FieldType      string
	SortOrder      int64
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Release struct {
	ID            int64
	ServiceID     int64
	EnvironmentID int64
	Ref           string
	ReleasedAt    string
	ReleaseUrl    sql.NullString
}

type ReleaseCommit struct {
	ReleaseID int64
	CommitID  int64
}

type Service struct {
	ID              int64
	Name            string
	IntegrationType string
	Description     sql.NullString
	Context         sql.NullString
	Team            sql.NullString
	RepoUrl         sql.NullString
	LogsUrl         sql.NullString
	EndpointUrl     sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type ServiceField struct {
	ID        int64
	ServiceID int64
	Label     string
	Value     string
	SortOrder int64
}

type ServiceInstance struct {
	ID                    int64
	ServiceID             int64
	EnvironmentID         int64
	Status                string
	LastDeployAt          sql.NullString
	DeployDurationSeconds sql.NullInt64
	Revision              sql.NullString
	CommitSha             sql.NullString
	CommitUrl             sql.NullString
	CommitIndex           sql.NullInt64
	ActionLabel           sql.NullString
	ActionKind            sql.NullString
	ActionDisabled        int64
	CreatedAt             sql.NullTime
	UpdatedAt             sql.NullTime
}
