// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fr0stylo/ddash/internal/app/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAppStore creates a new instance of MockAppStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppStore {
	mock := &MockAppStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAppStore is an autogenerated mock type for the AppStore type
type MockAppStore struct {
	mock.Mock
}

type MockAppStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppStore) EXPECT() *MockAppStore_Expecter {
	return &MockAppStore_Expecter{mock: &_m.Mock}
}

// CountOrganizationOwners provides a mock function for the type MockAppStore
func (_mock *MockAppStore) CountOrganizationOwners(ctx context.Context, organizationID int64) (int64, error) {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for CountOrganizationOwners")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return returnFunc(ctx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppStore_CountOrganizationOwners_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountOrganizationOwners'
type MockAppStore_CountOrganizationOwners_Call struct {
	*mock.Call
}

// CountOrganizationOwners is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
func (_e *MockAppStore_Expecter) CountOrganizationOwners(ctx interface{}, organizationID interface{}) *MockAppStore_CountOrganizationOwners_Call {
	return &MockAppStore_CountOrganizationOwners_Call{Call: _e.mock.On("CountOrganizationOwners", ctx, organizationID)}
}

func (_c *MockAppStore_CountOrganizationOwners_Call) Run(run func(ctx context.Context, organizationID int64)) *MockAppStore_CountOrganizationOwners_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppStore_CountOrganizationOwners_Call) Return(n int64, err error) *MockAppStore_CountOrganizationOwners_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAppStore_CountOrganizationOwners_Call) RunAndReturn(run func(ctx context.Context, organizationID int64) (int64, error)) *MockAppStore_CountOrganizationOwners_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrganization provides a mock function for the type MockAppStore
func (_mock *MockAppStore) CreateOrganization(ctx context.Context, params ports.CreateOrganizationInput) (ports.Organization, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganization")
	}

	var r0 ports.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.CreateOrganizationInput) (ports.Organization, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.CreateOrganizationInput) ports.Organization); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(ports.Organization)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.CreateOrganizationInput) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppStore_CreateOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrganization'
type MockAppStore_CreateOrganization_Call struct {
	*mock.Call
}

// CreateOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - params ports.CreateOrganizationInput
func (_e *MockAppStore_Expecter) CreateOrganization(ctx interface{}, params interface{}) *MockAppStore_CreateOrganization_Call {
	return &MockAppStore_CreateOrganization_Call{Call: _e.mock.On("CreateOrganization", ctx, params)}
}

func (_c *MockAppStore_CreateOrganization_Call) Run(run func(ctx context.Context, params ports.CreateOrganizationInput)) *MockAppStore_CreateOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.CreateOrganizationInput
		if args[1] != nil {
			arg1 = args[1].(ports.CreateOrganizationInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppStore_CreateOrganization_Call) Return(organization ports.Organization, err error) *MockAppStore_CreateOrganization_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *MockAppStore_CreateOrganization_Call) RunAndReturn(run func(ctx context.Context, params ports.CreateOrganizationInput) (ports.Organization, error)) *MockAppStore_CreateOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrganization provides a mock function for the type MockAppStore
func (_mock *MockAppStore) DeleteOrganization(ctx context.Context, organizationID int64) error {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrganization")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAppStore_DeleteOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrganization'
type MockAppStore_DeleteOrganization_Call struct {
	*mock.Call
}

// DeleteOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
func (_e *MockAppStore_Expecter) DeleteOrganization(ctx interface{}, organizationID interface{}) *MockAppStore_DeleteOrganization_Call {
	return &MockAppStore_DeleteOrganization_Call{Call: _e.mock.On("DeleteOrganization", ctx, organizationID)}
}

func (_c *MockAppStore_DeleteOrganization_Call) Run(run func(ctx context.Context, organizationID int64)) *MockAppStore_DeleteOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppStore_DeleteOrganization_Call) Return(err error) *MockAppStore_DeleteOrganization_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAppStore_DeleteOrganization_Call) RunAndReturn(run func(ctx context.Context, organizationID int64) error) *MockAppStore_DeleteOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrganizationMember provides a mock function for the type MockAppStore
func (_mock *MockAppStore) DeleteOrganizationMember(ctx context.Context, organizationID int64, userID int64) error {
	ret := _mock.Called(ctx, organizationID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrganizationMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, organizationID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAppStore_DeleteOrganizationMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrganizationMember'
type MockAppStore_DeleteOrganizationMember_Call struct {
	*mock.Call
}

// DeleteOrganizationMember is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
//   - userID int64
func (_e *MockAppStore_Expecter) DeleteOrganizationMember(ctx interface{}, organizationID interface{}, userID interface{}) *MockAppStore_DeleteOrganizationMember_Call {
	return &MockAppStore_DeleteOrganizationMember_Call{Call: _e.mock.On("DeleteOrganizationMember", ctx, organizationID, userID)}
}

func (_c *MockAppStore_DeleteOrganizationMember_Call) Run(run func(ctx context.Context, organizationID int64, userID int64)) *MockAppStore_DeleteOrganizationMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAppStore_DeleteOrganizationMember_Call) Return(err error) *MockAppStore_DeleteOrganizationMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAppStore_DeleteOrganizationMember_Call) RunAndReturn(run func(ctx context.Context, organizationID int64, userID int64) error) *MockAppStore_DeleteOrganizationMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetDefaultOrganization provides a mock function for the type MockAppStore
func (_mock *MockAppStore) GetDefaultOrganization(ctx context.Context) (ports.Organization, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultOrganization")
	}

	var r0 ports.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (ports.Organization, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) ports.Organization); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(ports.Organization)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppStore_GetDefaultOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultOrganization'
type MockAppStore_GetDefaultOrganization_Call struct {
	*mock.Call
}

// GetDefaultOrganization is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAppStore_Expecter) GetDefaultOrganization(ctx interface{}) *MockAppStore_GetDefaultOrganization_Call {
	return &MockAppStore_GetDefaultOrganization_Call{Call: _e.mock.On("GetDefaultOrganization", ctx)}
}

func (_c *MockAppStore_GetDefaultOrganization_Call) Run(run func(ctx context.Context)) *MockAppStore_GetDefaultOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppStore_GetDefaultOrganization_Call) Return(organization ports.Organization, err error) *MockAppStore_GetDefaultOrganization_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *MockAppStore_GetDefaultOrganization_Call) RunAndReturn(run func(ctx context.Context) (ports.Organization, error)) *MockAppStore_GetDefaultOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationByID provides a mock function for the type MockAppStore
func (_mock *MockAppStore) GetOrganizationByID(ctx context.Context, id int64) (ports.Organization, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationByID")
	}

	var r0 ports.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (ports.Organization, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ports.Organization); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(ports.Organization)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppStore_GetOrganizationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationByID'
type MockAppStore_GetOrganizationByID_Call struct {
	*mock.Call
}

// GetOrganizationByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockAppStore_Expecter) GetOrganizationByID(ctx interface{}, id interface{}) *MockAppStore_GetOrganizationByID_Call {
	return &MockAppStore_GetOrganizationByID_Call{Call: _e.mock.On("GetOrganizationByID", ctx, id)}
}

func (_c *MockAppStore_GetOrganizationByID_Call) Run(run func(ctx context.Context, id int64)) *MockAppStore_GetOrganizationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppStore_GetOrganizationByID_Call) Return(organization ports.Organization, err error) *MockAppStore_GetOrganizationByID_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *MockAppStore_GetOrganizationByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (ports.Organization, error)) *MockAppStore_GetOrganizationByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationByJoinCode provides a mock function for the type MockAppStore
func (_mock *MockAppStore) GetOrganizationByJoinCode(ctx context.Context, joinCode string) (ports.Organization, error) {
	ret := _mock.Called(ctx, joinCode)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationByJoinCode")
	}

	var r0 ports.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (ports.Organization, error)); ok {
		return returnFunc(ctx, joinCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ports.Organization); ok {
		r0 = returnFunc(ctx, joinCode)
	} else {
		r0 = ret.Get(0).(ports.Organization)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, joinCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppStore_GetOrganizationByJoinCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationByJoinCode'
type MockAppStore_GetOrganizationByJoinCode_Call struct {
	*mock.Call
}

// GetOrganizationByJoinCode is a helper method to define mock.On call
//   - ctx context.Context
//   - joinCode string
func (_e *MockAppStore_Expecter) GetOrganizationByJoinCode(ctx interface{}, joinCode interface{}) *MockAppStore_GetOrganizationByJoinCode_Call {
	return &MockAppStore_GetOrganizationByJoinCode_Call{Call: _e.mock.On("GetOrganizationByJoinCode", ctx, joinCode)}
}

func (_c *MockAppStore_GetOrganizationByJoinCode_Call) Run(run func(ctx context.Context, joinCode string)) *MockAppStore_GetOrganizationByJoinCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppStore_GetOrganizationByJoinCode_Call) Return(organization ports.Organization, err error) *MockAppStore_GetOrganizationByJoinCode_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *MockAppStore_GetOrganizationByJoinCode_Call) RunAndReturn(run func(ctx context.Context, joinCode string) (ports.Organization, error)) *MockAppStore_GetOrganizationByJoinCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganizationMemberRole provides a mock function for the type MockAppStore
func (_mock *MockAppStore) GetOrganizationMemberRole(ctx context.Context, organizationID int64, userID int64) (string, error) {
	ret := _mock.Called(ctx, organizationID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationMemberRole")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (string, error)); ok {
		return returnFunc(ctx, organizationID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) string); ok {
		r0 = returnFunc(ctx, organizationID, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, organizationID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppStore_GetOrganizationMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationMemberRole'
type MockAppStore_GetOrganizationMemberRole_Call struct {
	*mock.Call
}

// GetOrganizationMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
//   - userID int64
func (_e *MockAppStore_Expecter) GetOrganizationMemberRole(ctx interface{}, organizationID interface{}, userID interface{}) *MockAppStore_GetOrganizationMemberRole_Call {
	return &MockAppStore_GetOrganizationMemberRole_Call{Call: _e.mock.On("GetOrganizationMemberRole", ctx, organizationID, userID)}
}

func (_c *MockAppStore_GetOrganizationMemberRole_Call) Run(run func(ctx context.Context, organizationID int64, userID int64)) *MockAppStore_GetOrganizationMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAppStore_GetOrganizationMemberRole_Call) Return(s string, err error) *MockAppStore_GetOrganizationMemberRole_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAppStore_GetOrganizationMemberRole_Call) RunAndReturn(run func(ctx context.Context, organizationID int64, userID int64) (string, error)) *MockAppStore_GetOrganizationMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmailOrNickname provides a mock function for the type MockAppStore
func (_mock *MockAppStore) GetUserByEmailOrNickname(ctx context.Context, email string, nickname string) (ports.User, error) {
	ret := _mock.Called(ctx, email, nickname)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmailOrNickname")
	}

	var r0 ports.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (ports.User, error)); ok {
		return returnFunc(ctx, email, nickname)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ports.User); ok {
		r0 = returnFunc(ctx, email, nickname)
	} else {
		r0 = ret.Get(0).(ports.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, nickname)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppStore_GetUserByEmailOrNickname_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmailOrNickname'
type MockAppStore_GetUserByEmailOrNickname_Call struct {
	*mock.Call
}

// GetUserByEmailOrNickname is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - nickname string
func (_e *MockAppStore_Expecter) GetUserByEmailOrNickname(ctx interface{}, email interface{}, nickname interface{}) *MockAppStore_GetUserByEmailOrNickname_Call {
	return &MockAppStore_GetUserByEmailOrNickname_Call{Call: _e.mock.On("GetUserByEmailOrNickname", ctx, email, nickname)}
}

func (_c *MockAppStore_GetUserByEmailOrNickname_Call) Run(run func(ctx context.Context, email string, nickname string)) *MockAppStore_GetUserByEmailOrNickname_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAppStore_GetUserByEmailOrNickname_Call) Return(user ports.User, err error) *MockAppStore_GetUserByEmailOrNickname_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAppStore_GetUserByEmailOrNickname_Call) RunAndReturn(run func(ctx context.Context, email string, nickname string) (ports.User, error)) *MockAppStore_GetUserByEmailOrNickname_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockAppStore
func (_mock *MockAppStore) GetUserByID(ctx context.Context, id int64) (ports.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 ports.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (ports.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ports.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(ports.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppStore_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockAppStore_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockAppStore_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockAppStore_GetUserByID_Call {
	return &MockAppStore_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockAppStore_GetUserByID_Call) Run(run func(ctx context.Context, id int64)) *MockAppStore_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppStore_GetUserByID_Call) Return(user ports.User, err error) *MockAppStore_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAppStore_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (ports.User, error)) *MockAppStore_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListDistinctServiceEnvironmentsFromEvents provides a mock function for the type MockAppStore
func (_mock *MockAppStore) ListDistinctServiceEnvironmentsFromEvents(ctx context.Context, organizationID int64) ([]string, error) {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListDistinctServiceEnvironmentsFromEvents")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]string, error)); ok {
		return returnFunc(ctx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []string); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppStore_ListDistinctServiceEnvironmentsFromEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDistinctServiceEnvironmentsFromEvents'
type MockAppStore_ListDistinctServiceEnvironmentsFromEvents_Call struct {
	*mock.Call
}

// ListDistinctServiceEnvironmentsFromEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
func (_e *MockAppStore_Expecter) ListDistinctServiceEnvironmentsFromEvents(ctx interface{}, organizationID interface{}) *MockAppStore_ListDistinctServiceEnvironmentsFromEvents_Call {
	return &MockAppStore_ListDistinctServiceEnvironmentsFromEvents_Call{Call: _e.mock.On("ListDistinctServiceEnvironmentsFromEvents", ctx, organizationID)}
}

func (_c *MockAppStore_ListDistinctServiceEnvironmentsFromEvents_Call) Run(run func(ctx context.Context, organizationID int64)) *MockAppStore_ListDistinctServiceEnvironmentsFromEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppStore_ListDistinctServiceEnvironmentsFromEvents_Call) Return(strings []string, err error) *MockAppStore_ListDistinctServiceEnvironmentsFromEvents_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockAppStore_ListDistinctServiceEnvironmentsFromEvents_Call) RunAndReturn(run func(ctx context.Context, organizationID int64) ([]string, error)) *MockAppStore_ListDistinctServiceEnvironmentsFromEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrganizationEnvironmentPriorities provides a mock function for the type MockAppStore
func (_mock *MockAppStore) ListOrganizationEnvironmentPriorities(ctx context.Context, organizationID int64) ([]string, error) {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListOrganizationEnvironmentPriorities")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]string, error)); ok {
		return returnFunc(ctx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []string); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppStore_ListOrganizationEnvironmentPriorities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrganizationEnvironmentPriorities'
type MockAppStore_ListOrganizationEnvironmentPriorities_Call struct {
	*mock.Call
}

// ListOrganizationEnvironmentPriorities is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
func (_e *MockAppStore_Expecter) ListOrganizationEnvironmentPriorities(ctx interface{}, organizationID interface{}) *MockAppStore_ListOrganizationEnvironmentPriorities_Call {
	return &MockAppStore_ListOrganizationEnvironmentPriorities_Call{Call: _e.mock.On("ListOrganizationEnvironmentPriorities", ctx, organizationID)}
}

func (_c *MockAppStore_ListOrganizationEnvironmentPriorities_Call) Run(run func(ctx context.Context, organizationID int64)) *MockAppStore_ListOrganizationEnvironmentPriorities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppStore_ListOrganizationEnvironmentPriorities_Call) Return(strings []string, err error) *MockAppStore_ListOrganizationEnvironmentPriorities_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockAppStore_ListOrganizationEnvironmentPriorities_Call) RunAndReturn(run func(ctx context.Context, organizationID int64) ([]string, error)) *MockAppStore_ListOrganizationEnvironmentPriorities_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrganizationFeatures provides a mock function for the type MockAppStore
func (_mock *MockAppStore) ListOrganizationFeatures(ctx context.Context, organizationID int64) ([]ports.OrganizationFeature, error) {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListOrganizationFeatures")
	}

	var r0 []ports.OrganizationFeature
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]ports.OrganizationFeature, error)); ok {
		return returnFunc(ctx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []ports.OrganizationFeature); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.OrganizationFeature)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppStore_ListOrganizationFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrganizationFeatures'
type MockAppStore_ListOrganizationFeatures_Call struct {
	*mock.Call
}

// ListOrganizationFeatures is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
func (_e *MockAppStore_Expecter) ListOrganizationFeatures(ctx interface{}, organizationID interface{}) *MockAppStore_ListOrganizationFeatures_Call {
	return &MockAppStore_ListOrganizationFeatures_Call{Call: _e.mock.On("ListOrganizationFeatures", ctx, organizationID)}
}

func (_c *MockAppStore_ListOrganizationFeatures_Call) Run(run func(ctx context.Context, organizationID int64)) *MockAppStore_ListOrganizationFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppStore_ListOrganizationFeatures_Call) Return(organizationFeatures []ports.OrganizationFeature, err error) *MockAppStore_ListOrganizationFeatures_Call {
	_c.Call.Return(organizationFeatures, err)
	return _c
}

func (_c *MockAppStore_ListOrganizationFeatures_Call) RunAndReturn(run func(ctx context.Context, organizationID int64) ([]ports.OrganizationFeature, error)) *MockAppStore_ListOrganizationFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrganizationMembers provides a mock function for the type MockAppStore
func (_mock *MockAppStore) ListOrganizationMembers(ctx context.Context, organizationID int64) ([]ports.OrganizationMember, error) {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListOrganizationMembers")
	}

	var r0 []ports.OrganizationMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]ports.OrganizationMember, error)); ok {
		return returnFunc(ctx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []ports.OrganizationMember); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.OrganizationMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppStore_ListOrganizationMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrganizationMembers'
type MockAppStore_ListOrganizationMembers_Call struct {
	*mock.Call
}

// ListOrganizationMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
func (_e *MockAppStore_Expecter) ListOrganizationMembers(ctx interface{}, organizationID interface{}) *MockAppStore_ListOrganizationMembers_Call {
	return &MockAppStore_ListOrganizationMembers_Call{Call: _e.mock.On("ListOrganizationMembers", ctx, organizationID)}
}

func (_c *MockAppStore_ListOrganizationMembers_Call) Run(run func(ctx context.Context, organizationID int64)) *MockAppStore_ListOrganizationMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppStore_ListOrganizationMembers_Call) Return(organizationMembers []ports.OrganizationMember, err error) *MockAppStore_ListOrganizationMembers_Call {
	_c.Call.Return(organizationMembers, err)
	return _c
}

func (_c *MockAppStore_ListOrganizationMembers_Call) RunAndReturn(run func(ctx context.Context, organizationID int64) ([]ports.OrganizationMember, error)) *MockAppStore_ListOrganizationMembers_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrganizationPreferences provides a mock function for the type MockAppStore
func (_mock *MockAppStore) ListOrganizationPreferences(ctx context.Context, organizationID int64) ([]ports.OrganizationPreference, error) {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListOrganizationPreferences")
	}

	var r0 []ports.OrganizationPreference
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]ports.OrganizationPreference, error)); ok {
		return returnFunc(ctx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []ports.OrganizationPreference); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.OrganizationPreference)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppStore_ListOrganizationPreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrganizationPreferences'
type MockAppStore_ListOrganizationPreferences_Call struct {
	*mock.Call
}

// ListOrganizationPreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
func (_e *MockAppStore_Expecter) ListOrganizationPreferences(ctx interface{}, organizationID interface{}) *MockAppStore_ListOrganizationPreferences_Call {
	return &MockAppStore_ListOrganizationPreferences_Call{Call: _e.mock.On("ListOrganizationPreferences", ctx, organizationID)}
}

func (_c *MockAppStore_ListOrganizationPreferences_Call) Run(run func(ctx context.Context, organizationID int64)) *MockAppStore_ListOrganizationPreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppStore_ListOrganizationPreferences_Call) Return(organizationPreferences []ports.OrganizationPreference, err error) *MockAppStore_ListOrganizationPreferences_Call {
	_c.Call.Return(organizationPreferences, err)
	return _c
}

func (_c *MockAppStore_ListOrganizationPreferences_Call) RunAndReturn(run func(ctx context.Context, organizationID int64) ([]ports.OrganizationPreference, error)) *MockAppStore_ListOrganizationPreferences_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrganizationRequiredFields provides a mock function for the type MockAppStore
func (_mock *MockAppStore) ListOrganizationRequiredFields(ctx context.Context, organizationID int64) ([]ports.RequiredField, error) {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListOrganizationRequiredFields")
	}

	var r0 []ports.RequiredField
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]ports.RequiredField, error)); ok {
		return returnFunc(ctx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []ports.RequiredField); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.RequiredField)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppStore_ListOrganizationRequiredFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrganizationRequiredFields'
type MockAppStore_ListOrganizationRequiredFields_Call struct {
	*mock.Call
}

// ListOrganizationRequiredFields is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
func (_e *MockAppStore_Expecter) ListOrganizationRequiredFields(ctx interface{}, organizationID interface{}) *MockAppStore_ListOrganizationRequiredFields_Call {
	return &MockAppStore_ListOrganizationRequiredFields_Call{Call: _e.mock.On("ListOrganizationRequiredFields", ctx, organizationID)}
}

func (_c *MockAppStore_ListOrganizationRequiredFields_Call) Run(run func(ctx context.Context, organizationID int64)) *MockAppStore_ListOrganizationRequiredFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppStore_ListOrganizationRequiredFields_Call) Return(requiredFields []ports.RequiredField, err error) *MockAppStore_ListOrganizationRequiredFields_Call {
	_c.Call.Return(requiredFields, err)
	return _c
}

func (_c *MockAppStore_ListOrganizationRequiredFields_Call) RunAndReturn(run func(ctx context.Context, organizationID int64) ([]ports.RequiredField, error)) *MockAppStore_ListOrganizationRequiredFields_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrganizations provides a mock function for the type MockAppStore
func (_mock *MockAppStore) ListOrganizations(ctx context.Context) ([]ports.Organization, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListOrganizations")
	}

	var r0 []ports.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]ports.Organization, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []ports.Organization); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppStore_ListOrganizations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrganizations'
type MockAppStore_ListOrganizations_Call struct {
	*mock.Call
}

// ListOrganizations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAppStore_Expecter) ListOrganizations(ctx interface{}) *MockAppStore_ListOrganizations_Call {
	return &MockAppStore_ListOrganizations_Call{Call: _e.mock.On("ListOrganizations", ctx)}
}

func (_c *MockAppStore_ListOrganizations_Call) Run(run func(ctx context.Context)) *MockAppStore_ListOrganizations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppStore_ListOrganizations_Call) Return(organizations []ports.Organization, err error) *MockAppStore_ListOrganizations_Call {
	_c.Call.Return(organizations, err)
	return _c
}

func (_c *MockAppStore_ListOrganizations_Call) RunAndReturn(run func(ctx context.Context) ([]ports.Organization, error)) *MockAppStore_ListOrganizations_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrganizationsByUser provides a mock function for the type MockAppStore
func (_mock *MockAppStore) ListOrganizationsByUser(ctx context.Context, userID int64) ([]ports.Organization, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListOrganizationsByUser")
	}

	var r0 []ports.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]ports.Organization, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []ports.Organization); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppStore_ListOrganizationsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrganizationsByUser'
type MockAppStore_ListOrganizationsByUser_Call struct {
	*mock.Call
}

// ListOrganizationsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAppStore_Expecter) ListOrganizationsByUser(ctx interface{}, userID interface{}) *MockAppStore_ListOrganizationsByUser_Call {
	return &MockAppStore_ListOrganizationsByUser_Call{Call: _e.mock.On("ListOrganizationsByUser", ctx, userID)}
}

func (_c *MockAppStore_ListOrganizationsByUser_Call) Run(run func(ctx context.Context, userID int64)) *MockAppStore_ListOrganizationsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppStore_ListOrganizationsByUser_Call) Return(organizations []ports.Organization, err error) *MockAppStore_ListOrganizationsByUser_Call {
	_c.Call.Return(organizations, err)
	return _c
}

func (_c *MockAppStore_ListOrganizationsByUser_Call) RunAndReturn(run func(ctx context.Context, userID int64) ([]ports.Organization, error)) *MockAppStore_ListOrganizationsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingOrganizationJoinRequests provides a mock function for the type MockAppStore
func (_mock *MockAppStore) ListPendingOrganizationJoinRequests(ctx context.Context, organizationID int64) ([]ports.OrganizationJoinRequest, error) {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingOrganizationJoinRequests")
	}

	var r0 []ports.OrganizationJoinRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]ports.OrganizationJoinRequest, error)); ok {
		return returnFunc(ctx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []ports.OrganizationJoinRequest); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.OrganizationJoinRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppStore_ListPendingOrganizationJoinRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingOrganizationJoinRequests'
type MockAppStore_ListPendingOrganizationJoinRequests_Call struct {
	*mock.Call
}

// ListPendingOrganizationJoinRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
func (_e *MockAppStore_Expecter) ListPendingOrganizationJoinRequests(ctx interface{}, organizationID interface{}) *MockAppStore_ListPendingOrganizationJoinRequests_Call {
	return &MockAppStore_ListPendingOrganizationJoinRequests_Call{Call: _e.mock.On("ListPendingOrganizationJoinRequests", ctx, organizationID)}
}

func (_c *MockAppStore_ListPendingOrganizationJoinRequests_Call) Run(run func(ctx context.Context, organizationID int64)) *MockAppStore_ListPendingOrganizationJoinRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppStore_ListPendingOrganizationJoinRequests_Call) Return(organizationJoinRequests []ports.OrganizationJoinRequest, err error) *MockAppStore_ListPendingOrganizationJoinRequests_Call {
	_c.Call.Return(organizationJoinRequests, err)
	return _c
}

func (_c *MockAppStore_ListPendingOrganizationJoinRequests_Call) RunAndReturn(run func(ctx context.Context, organizationID int64) ([]ports.OrganizationJoinRequest, error)) *MockAppStore_ListPendingOrganizationJoinRequests_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceServiceMetadata provides a mock function for the type MockAppStore
func (_mock *MockAppStore) ReplaceServiceMetadata(ctx context.Context, organizationID int64, serviceName string, values []ports.MetadataValue) error {
	ret := _mock.Called(ctx, organizationID, serviceName, values)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceServiceMetadata")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, []ports.MetadataValue) error); ok {
		r0 = returnFunc(ctx, organizationID, serviceName, values)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAppStore_ReplaceServiceMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceServiceMetadata'
type MockAppStore_ReplaceServiceMetadata_Call struct {
	*mock.Call
}

// ReplaceServiceMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
//   - serviceName string
//   - values []ports.MetadataValue
func (_e *MockAppStore_Expecter) ReplaceServiceMetadata(ctx interface{}, organizationID interface{}, serviceName interface{}, values interface{}) *MockAppStore_ReplaceServiceMetadata_Call {
	return &MockAppStore_ReplaceServiceMetadata_Call{Call: _e.mock.On("ReplaceServiceMetadata", ctx, organizationID, serviceName, values)}
}

func (_c *MockAppStore_ReplaceServiceMetadata_Call) Run(run func(ctx context.Context, organizationID int64, serviceName string, values []ports.MetadataValue)) *MockAppStore_ReplaceServiceMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []ports.MetadataValue
		if args[3] != nil {
			arg3 = args[3].([]ports.MetadataValue)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAppStore_ReplaceServiceMetadata_Call) Return(err error) *MockAppStore_ReplaceServiceMetadata_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAppStore_ReplaceServiceMetadata_Call) RunAndReturn(run func(ctx context.Context, organizationID int64, serviceName string, values []ports.MetadataValue) error) *MockAppStore_ReplaceServiceMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// SetOrganizationJoinRequestStatus provides a mock function for the type MockAppStore
func (_mock *MockAppStore) SetOrganizationJoinRequestStatus(ctx context.Context, organizationID int64, userID int64, status string, reviewedBy int64) error {
	ret := _mock.Called(ctx, organizationID, userID, status, reviewedBy)

	if len(ret) == 0 {
		panic("no return value specified for SetOrganizationJoinRequestStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string, int64) error); ok {
		r0 = returnFunc(ctx, organizationID, userID, status, reviewedBy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAppStore_SetOrganizationJoinRequestStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOrganizationJoinRequestStatus'
type MockAppStore_SetOrganizationJoinRequestStatus_Call struct {
	*mock.Call
}

// SetOrganizationJoinRequestStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
//   - userID int64
//   - status string
//   - reviewedBy int64
func (_e *MockAppStore_Expecter) SetOrganizationJoinRequestStatus(ctx interface{}, organizationID interface{}, userID interface{}, status interface{}, reviewedBy interface{}) *MockAppStore_SetOrganizationJoinRequestStatus_Call {
	return &MockAppStore_SetOrganizationJoinRequestStatus_Call{Call: _e.mock.On("SetOrganizationJoinRequestStatus", ctx, organizationID, userID, status, reviewedBy)}
}

func (_c *MockAppStore_SetOrganizationJoinRequestStatus_Call) Run(run func(ctx context.Context, organizationID int64, userID int64, status string, reviewedBy int64)) *MockAppStore_SetOrganizationJoinRequestStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAppStore_SetOrganizationJoinRequestStatus_Call) Return(err error) *MockAppStore_SetOrganizationJoinRequestStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAppStore_SetOrganizationJoinRequestStatus_Call) RunAndReturn(run func(ctx context.Context, organizationID int64, userID int64, status string, reviewedBy int64) error) *MockAppStore_SetOrganizationJoinRequestStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrganizationEnabled provides a mock function for the type MockAppStore
func (_mock *MockAppStore) UpdateOrganizationEnabled(ctx context.Context, organizationID int64, enabled bool) error {
	ret := _mock.Called(ctx, organizationID, enabled)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrganizationEnabled")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool) error); ok {
		r0 = returnFunc(ctx, organizationID, enabled)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAppStore_UpdateOrganizationEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrganizationEnabled'
type MockAppStore_UpdateOrganizationEnabled_Call struct {
	*mock.Call
}

// UpdateOrganizationEnabled is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
//   - enabled bool
func (_e *MockAppStore_Expecter) UpdateOrganizationEnabled(ctx interface{}, organizationID interface{}, enabled interface{}) *MockAppStore_UpdateOrganizationEnabled_Call {
	return &MockAppStore_UpdateOrganizationEnabled_Call{Call: _e.mock.On("UpdateOrganizationEnabled", ctx, organizationID, enabled)}
}

func (_c *MockAppStore_UpdateOrganizationEnabled_Call) Run(run func(ctx context.Context, organizationID int64, enabled bool)) *MockAppStore_UpdateOrganizationEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAppStore_UpdateOrganizationEnabled_Call) Return(err error) *MockAppStore_UpdateOrganizationEnabled_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAppStore_UpdateOrganizationEnabled_Call) RunAndReturn(run func(ctx context.Context, organizationID int64, enabled bool) error) *MockAppStore_UpdateOrganizationEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrganizationName provides a mock function for the type MockAppStore
func (_mock *MockAppStore) UpdateOrganizationName(ctx context.Context, organizationID int64, name string) error {
	ret := _mock.Called(ctx, organizationID, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrganizationName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, organizationID, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAppStore_UpdateOrganizationName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrganizationName'
type MockAppStore_UpdateOrganizationName_Call struct {
	*mock.Call
}

// UpdateOrganizationName is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
//   - name string
func (_e *MockAppStore_Expecter) UpdateOrganizationName(ctx interface{}, organizationID interface{}, name interface{}) *MockAppStore_UpdateOrganizationName_Call {
	return &MockAppStore_UpdateOrganizationName_Call{Call: _e.mock.On("UpdateOrganizationName", ctx, organizationID, name)}
}

func (_c *MockAppStore_UpdateOrganizationName_Call) Run(run func(ctx context.Context, organizationID int64, name string)) *MockAppStore_UpdateOrganizationName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAppStore_UpdateOrganizationName_Call) Return(err error) *MockAppStore_UpdateOrganizationName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAppStore_UpdateOrganizationName_Call) RunAndReturn(run func(ctx context.Context, organizationID int64, name string) error) *MockAppStore_UpdateOrganizationName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrganizationSettings provides a mock function for the type MockAppStore
func (_mock *MockAppStore) UpdateOrganizationSettings(ctx context.Context, organizationID int64, params ports.OrganizationSettingsUpdate) error {
	ret := _mock.Called(ctx, organizationID, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrganizationSettings")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, ports.OrganizationSettingsUpdate) error); ok {
		r0 = returnFunc(ctx, organizationID, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAppStore_UpdateOrganizationSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrganizationSettings'
type MockAppStore_UpdateOrganizationSettings_Call struct {
	*mock.Call
}

// UpdateOrganizationSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
//   - params ports.OrganizationSettingsUpdate
func (_e *MockAppStore_Expecter) UpdateOrganizationSettings(ctx interface{}, organizationID interface{}, params interface{}) *MockAppStore_UpdateOrganizationSettings_Call {
	return &MockAppStore_UpdateOrganizationSettings_Call{Call: _e.mock.On("UpdateOrganizationSettings", ctx, organizationID, params)}
}

func (_c *MockAppStore_UpdateOrganizationSettings_Call) Run(run func(ctx context.Context, organizationID int64, params ports.OrganizationSettingsUpdate)) *MockAppStore_UpdateOrganizationSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 ports.OrganizationSettingsUpdate
		if args[2] != nil {
			arg2 = args[2].(ports.OrganizationSettingsUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAppStore_UpdateOrganizationSettings_Call) Return(err error) *MockAppStore_UpdateOrganizationSettings_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAppStore_UpdateOrganizationSettings_Call) RunAndReturn(run func(ctx context.Context, organizationID int64, params ports.OrganizationSettingsUpdate) error) *MockAppStore_UpdateOrganizationSettings_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertOrganizationJoinRequest provides a mock function for the type MockAppStore
func (_mock *MockAppStore) UpsertOrganizationJoinRequest(ctx context.Context, organizationID int64, userID int64, requestCode string) error {
	ret := _mock.Called(ctx, organizationID, userID, requestCode)

	if len(ret) == 0 {
		panic("no return value specified for UpsertOrganizationJoinRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string) error); ok {
		r0 = returnFunc(ctx, organizationID, userID, requestCode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAppStore_UpsertOrganizationJoinRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertOrganizationJoinRequest'
type MockAppStore_UpsertOrganizationJoinRequest_Call struct {
	*mock.Call
}

// UpsertOrganizationJoinRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
//   - userID int64
//   - requestCode string
func (_e *MockAppStore_Expecter) UpsertOrganizationJoinRequest(ctx interface{}, organizationID interface{}, userID interface{}, requestCode interface{}) *MockAppStore_UpsertOrganizationJoinRequest_Call {
	return &MockAppStore_UpsertOrganizationJoinRequest_Call{Call: _e.mock.On("UpsertOrganizationJoinRequest", ctx, organizationID, userID, requestCode)}
}

func (_c *MockAppStore_UpsertOrganizationJoinRequest_Call) Run(run func(ctx context.Context, organizationID int64, userID int64, requestCode string)) *MockAppStore_UpsertOrganizationJoinRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAppStore_UpsertOrganizationJoinRequest_Call) Return(err error) *MockAppStore_UpsertOrganizationJoinRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAppStore_UpsertOrganizationJoinRequest_Call) RunAndReturn(run func(ctx context.Context, organizationID int64, userID int64, requestCode string) error) *MockAppStore_UpsertOrganizationJoinRequest_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertOrganizationMember provides a mock function for the type MockAppStore
func (_mock *MockAppStore) UpsertOrganizationMember(ctx context.Context, organizationID int64, userID int64, role string) error {
	ret := _mock.Called(ctx, organizationID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpsertOrganizationMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, string) error); ok {
		r0 = returnFunc(ctx, organizationID, userID, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAppStore_UpsertOrganizationMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertOrganizationMember'
type MockAppStore_UpsertOrganizationMember_Call struct {
	*mock.Call
}

// UpsertOrganizationMember is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
//   - userID int64
//   - role string
func (_e *MockAppStore_Expecter) UpsertOrganizationMember(ctx interface{}, organizationID interface{}, userID interface{}, role interface{}) *MockAppStore_UpsertOrganizationMember_Call {
	return &MockAppStore_UpsertOrganizationMember_Call{Call: _e.mock.On("UpsertOrganizationMember", ctx, organizationID, userID, role)}
}

func (_c *MockAppStore_UpsertOrganizationMember_Call) Run(run func(ctx context.Context, organizationID int64, userID int64, role string)) *MockAppStore_UpsertOrganizationMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAppStore_UpsertOrganizationMember_Call) Return(err error) *MockAppStore_UpsertOrganizationMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAppStore_UpsertOrganizationMember_Call) RunAndReturn(run func(ctx context.Context, organizationID int64, userID int64, role string) error) *MockAppStore_UpsertOrganizationMember_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUser provides a mock function for the type MockAppStore
func (_mock *MockAppStore) UpsertUser(ctx context.Context, input ports.UpsertUserInput) (ports.User, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUser")
	}

	var r0 ports.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.UpsertUserInput) (ports.User, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.UpsertUserInput) ports.User); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(ports.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.UpsertUserInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAppStore_UpsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUser'
type MockAppStore_UpsertUser_Call struct {
	*mock.Call
}

// UpsertUser is a helper method to define mock.On call
//   - ctx context.Context
//   - input ports.UpsertUserInput
func (_e *MockAppStore_Expecter) UpsertUser(ctx interface{}, input interface{}) *MockAppStore_UpsertUser_Call {
	return &MockAppStore_UpsertUser_Call{Call: _e.mock.On("UpsertUser", ctx, input)}
}

func (_c *MockAppStore_UpsertUser_Call) Run(run func(ctx context.Context, input ports.UpsertUserInput)) *MockAppStore_UpsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.UpsertUserInput
		if args[1] != nil {
			arg1 = args[1].(ports.UpsertUserInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAppStore_UpsertUser_Call) Return(user ports.User, err error) *MockAppStore_UpsertUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAppStore_UpsertUser_Call) RunAndReturn(run func(ctx context.Context, input ports.UpsertUserInput) (ports.User, error)) *MockAppStore_UpsertUser_Call {
	_c.Call.Return(run)
	return _c
}
