// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fr0stylo/ddash/internal/app/domain"
	"github.com/fr0stylo/ddash/internal/app/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServiceQueryStore creates a new instance of MockServiceQueryStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceQueryStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceQueryStore {
	mock := &MockServiceQueryStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceQueryStore is an autogenerated mock type for the ServiceQueryStore type
type MockServiceQueryStore struct {
	mock.Mock
}

type MockServiceQueryStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceQueryStore) EXPECT() *MockServiceQueryStore_Expecter {
	return &MockServiceQueryStore_Expecter{mock: &_m.Mock}
}

// GetOrganizationRenderVersion provides a mock function for the type MockServiceQueryStore
func (_mock *MockServiceQueryStore) GetOrganizationRenderVersion(ctx context.Context, organizationID int64) (int64, error) {
	ret := _mock.Called(ctx, organizationID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationRenderVersion")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return returnFunc(ctx, organizationID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = returnFunc(ctx, organizationID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, organizationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceQueryStore_GetOrganizationRenderVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationRenderVersion'
type MockServiceQueryStore_GetOrganizationRenderVersion_Call struct {
	*mock.Call
}

// GetOrganizationRenderVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
func (_e *MockServiceQueryStore_Expecter) GetOrganizationRenderVersion(ctx interface{}, organizationID interface{}) *MockServiceQueryStore_GetOrganizationRenderVersion_Call {
	return &MockServiceQueryStore_GetOrganizationRenderVersion_Call{Call: _e.mock.On("GetOrganizationRenderVersion", ctx, organizationID)}
}

func (_c *MockServiceQueryStore_GetOrganizationRenderVersion_Call) Run(run func(ctx context.Context, organizationID int64)) *MockServiceQueryStore_GetOrganizationRenderVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceQueryStore_GetOrganizationRenderVersion_Call) Return(n int64, err error) *MockServiceQueryStore_GetOrganizationRenderVersion_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockServiceQueryStore_GetOrganizationRenderVersion_Call) RunAndReturn(run func(ctx context.Context, organizationID int64) (int64, error)) *MockServiceQueryStore_GetOrganizationRenderVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetServiceLatest provides a mock function for the type MockServiceQueryStore
func (_mock *MockServiceQueryStore) GetServiceLatest(ctx context.Context, organizationID int64, name string) (ports.ServiceLatest, error) {
	ret := _mock.Called(ctx, organizationID, name)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceLatest")
	}

	var r0 ports.ServiceLatest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (ports.ServiceLatest, error)); ok {
		return returnFunc(ctx, organizationID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) ports.ServiceLatest); ok {
		r0 = returnFunc(ctx, organizationID, name)
	} else {
		r0 = ret.Get(0).(ports.ServiceLatest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, organizationID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceQueryStore_GetServiceLatest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceLatest'
type MockServiceQueryStore_GetServiceLatest_Call struct {
	*mock.Call
}

// GetServiceLatest is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
//   - name string
func (_e *MockServiceQueryStore_Expecter) GetServiceLatest(ctx interface{}, organizationID interface{}, name interface{}) *MockServiceQueryStore_GetServiceLatest_Call {
	return &MockServiceQueryStore_GetServiceLatest_Call{Call: _e.mock.On("GetServiceLatest", ctx, organizationID, name)}
}

func (_c *MockServiceQueryStore_GetServiceLatest_Call) Run(run func(ctx context.Context, organizationID int64, name string)) *MockServiceQueryStore_GetServiceLatest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServiceQueryStore_GetServiceLatest_Call) Return(serviceLatest ports.ServiceLatest, err error) *MockServiceQueryStore_GetServiceLatest_Call {
	_c.Call.Return(serviceLatest, err)
	return _c
}

func (_c *MockServiceQueryStore_GetServiceLatest_Call) RunAndReturn(run func(ctx context.Context, organizationID int64, name string) (ports.ServiceLatest, error)) *MockServiceQueryStore_GetServiceLatest_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeploymentHistory provides a mock function for the type MockServiceQueryStore
func (_mock *MockServiceQueryStore) ListDeploymentHistory(ctx context.Context, organizationID int64, service string, limit int64) ([]domain.DeploymentRecord, error) {
	ret := _mock.Called(ctx, organizationID, service, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListDeploymentHistory")
	}

	var r0 []domain.DeploymentRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, int64) ([]domain.DeploymentRecord, error)); ok {
		return returnFunc(ctx, organizationID, service, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, int64) []domain.DeploymentRecord); ok {
		r0 = returnFunc(ctx, organizationID, service, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DeploymentRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, int64) error); ok {
		r1 = returnFunc(ctx, organizationID, service, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceQueryStore_ListDeploymentHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeploymentHistory'
type MockServiceQueryStore_ListDeploymentHistory_Call struct {
	*mock.Call
}

// ListDeploymentHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
//   - service string
//   - limit int64
func (_e *MockServiceQueryStore_Expecter) ListDeploymentHistory(ctx interface{}, organizationID interface{}, service interface{}, limit interface{}) *MockServiceQueryStore_ListDeploymentHistory_Call {
	return &MockServiceQueryStore_ListDeploymentHistory_Call{Call: _e.mock.On("ListDeploymentHistory", ctx, organizationID, service, limit)}
}

func (_c *MockServiceQueryStore_ListDeploymentHistory_Call) Run(run func(ctx context.Context, organizationID int64, service string, limit int64)) *MockServiceQueryStore_ListDeploymentHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockServiceQueryStore_ListDeploymentHistory_Call) Return(deploymentRecords []domain.DeploymentRecord, err error) *MockServiceQueryStore_ListDeploymentHistory_Call {
	_c.Call.Return(deploymentRecords, err)
	return _c
}

func (_c *MockServiceQueryStore_ListDeploymentHistory_Call) RunAndReturn(run func(ctx context.Context, organizationID int64, service string, limit int64) ([]domain.DeploymentRecord, error)) *MockServiceQueryStore_ListDeploymentHistory_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeployments provides a mock function for the type MockServiceQueryStore
func (_mock *MockServiceQueryStore) ListDeployments(ctx context.Context, organizationID int64, env string, service string) ([]domain.DeploymentRow, error) {
	ret := _mock.Called(ctx, organizationID, env, service)

	if len(ret) == 0 {
		panic("no return value specified for ListDeployments")
	}

	var r0 []domain.DeploymentRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) ([]domain.DeploymentRow, error)); ok {
		return returnFunc(ctx, organizationID, env, service)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) []domain.DeploymentRow); ok {
		r0 = returnFunc(ctx, organizationID, env, service)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DeploymentRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string) error); ok {
		r1 = returnFunc(ctx, organizationID, env, service)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceQueryStore_ListDeployments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeployments'
type MockServiceQueryStore_ListDeployments_Call struct {
	*mock.Call
}

// ListDeployments is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
//   - env string
//   - service string
func (_e *MockServiceQueryStore_Expecter) ListDeployments(ctx interface{}, organizationID interface{}, env interface{}, service interface{}) *MockServiceQueryStore_ListDeployments_Call {
	return &MockServiceQueryStore_ListDeployments_Call{Call: _e.mock.On("ListDeployments", ctx, organizationID, env, service)}
}

func (_c *MockServiceQueryStore_ListDeployments_Call) Run(run func(ctx context.Context, organizationID int64, env string, service string)) *MockServiceQueryStore_ListDeployments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockServiceQueryStore_ListDeployments_Call) Return(deploymentRows []domain.DeploymentRow, err error) *MockServiceQueryStore_ListDeployments_Call {
	_c.Call.Return(deploymentRows, err)
	return _c
}

func (_c *MockServiceQueryStore_ListDeployments_Call) RunAndReturn(run func(ctx context.Context, organizationID int64, env string, service string) ([]domain.DeploymentRow, error)) *MockServiceQueryStore_ListDeployments_Call {
	_c.Call.Return(run)
	return _c
}

// ListServiceEnvironments provides a mock function for the type MockServiceQueryStore
func (_mock *MockServiceQueryStore) ListServiceEnvironments(ctx context.Context, organizationID int64, service string) ([]domain.ServiceEnvironment, error) {
	ret := _mock.Called(ctx, organizationID, service)

	if len(ret) == 0 {
		panic("no return value specified for ListServiceEnvironments")
	}

	var r0 []domain.ServiceEnvironment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) ([]domain.ServiceEnvironment, error)); ok {
		return returnFunc(ctx, organizationID, service)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) []domain.ServiceEnvironment); ok {
		r0 = returnFunc(ctx, organizationID, service)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ServiceEnvironment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, organizationID, service)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceQueryStore_ListServiceEnvironments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServiceEnvironments'
type MockServiceQueryStore_ListServiceEnvironments_Call struct {
	*mock.Call
}

// ListServiceEnvironments is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
//   - service string
func (_e *MockServiceQueryStore_Expecter) ListServiceEnvironments(ctx interface{}, organizationID interface{}, service interface{}) *MockServiceQueryStore_ListServiceEnvironments_Call {
	return &MockServiceQueryStore_ListServiceEnvironments_Call{Call: _e.mock.On("ListServiceEnvironments", ctx, organizationID, service)}
}

func (_c *MockServiceQueryStore_ListServiceEnvironments_Call) Run(run func(ctx context.Context, organizationID int64, service string)) *MockServiceQueryStore_ListServiceEnvironments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServiceQueryStore_ListServiceEnvironments_Call) Return(serviceEnvironments []domain.ServiceEnvironment, err error) *MockServiceQueryStore_ListServiceEnvironments_Call {
	_c.Call.Return(serviceEnvironments, err)
	return _c
}

func (_c *MockServiceQueryStore_ListServiceEnvironments_Call) RunAndReturn(run func(ctx context.Context, organizationID int64, service string) ([]domain.ServiceEnvironment, error)) *MockServiceQueryStore_ListServiceEnvironments_Call {
	_c.Call.Return(run)
	return _c
}

// ListServiceInstances provides a mock function for the type MockServiceQueryStore
func (_mock *MockServiceQueryStore) ListServiceInstances(ctx context.Context, organizationID int64, env string) ([]domain.Service, error) {
	ret := _mock.Called(ctx, organizationID, env)

	if len(ret) == 0 {
		panic("no return value specified for ListServiceInstances")
	}

	var r0 []domain.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) ([]domain.Service, error)); ok {
		return returnFunc(ctx, organizationID, env)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) []domain.Service); ok {
		r0 = returnFunc(ctx, organizationID, env)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, organizationID, env)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceQueryStore_ListServiceInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServiceInstances'
type MockServiceQueryStore_ListServiceInstances_Call struct {
	*mock.Call
}

// ListServiceInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
//   - env string
func (_e *MockServiceQueryStore_Expecter) ListServiceInstances(ctx interface{}, organizationID interface{}, env interface{}) *MockServiceQueryStore_ListServiceInstances_Call {
	return &MockServiceQueryStore_ListServiceInstances_Call{Call: _e.mock.On("ListServiceInstances", ctx, organizationID, env)}
}

func (_c *MockServiceQueryStore_ListServiceInstances_Call) Run(run func(ctx context.Context, organizationID int64, env string)) *MockServiceQueryStore_ListServiceInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServiceQueryStore_ListServiceInstances_Call) Return(services []domain.Service, err error) *MockServiceQueryStore_ListServiceInstances_Call {
	_c.Call.Return(services, err)
	return _c
}

func (_c *MockServiceQueryStore_ListServiceInstances_Call) RunAndReturn(run func(ctx context.Context, organizationID int64, env string) ([]domain.Service, error)) *MockServiceQueryStore_ListServiceInstances_Call {
	_c.Call.Return(run)
	return _c
}
