// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fr0stylo/ddash/internal/app/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServiceAnalyticsStore creates a new instance of MockServiceAnalyticsStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceAnalyticsStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceAnalyticsStore {
	mock := &MockServiceAnalyticsStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceAnalyticsStore is an autogenerated mock type for the ServiceAnalyticsStore type
type MockServiceAnalyticsStore struct {
	mock.Mock
}

type MockServiceAnalyticsStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceAnalyticsStore) EXPECT() *MockServiceAnalyticsStore_Expecter {
	return &MockServiceAnalyticsStore_Expecter{mock: &_m.Mock}
}

// GetServiceCurrentState provides a mock function for the type MockServiceAnalyticsStore
func (_mock *MockServiceAnalyticsStore) GetServiceCurrentState(ctx context.Context, organizationID int64, service string) (ports.ServiceCurrentState, error) {
	ret := _mock.Called(ctx, organizationID, service)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceCurrentState")
	}

	var r0 ports.ServiceCurrentState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (ports.ServiceCurrentState, error)); ok {
		return returnFunc(ctx, organizationID, service)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) ports.ServiceCurrentState); ok {
		r0 = returnFunc(ctx, organizationID, service)
	} else {
		r0 = ret.Get(0).(ports.ServiceCurrentState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, organizationID, service)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceAnalyticsStore_GetServiceCurrentState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceCurrentState'
type MockServiceAnalyticsStore_GetServiceCurrentState_Call struct {
	*mock.Call
}

// GetServiceCurrentState is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
//   - service string
func (_e *MockServiceAnalyticsStore_Expecter) GetServiceCurrentState(ctx interface{}, organizationID interface{}, service interface{}) *MockServiceAnalyticsStore_GetServiceCurrentState_Call {
	return &MockServiceAnalyticsStore_GetServiceCurrentState_Call{Call: _e.mock.On("GetServiceCurrentState", ctx, organizationID, service)}
}

func (_c *MockServiceAnalyticsStore_GetServiceCurrentState_Call) Run(run func(ctx context.Context, organizationID int64, service string)) *MockServiceAnalyticsStore_GetServiceCurrentState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServiceAnalyticsStore_GetServiceCurrentState_Call) Return(serviceCurrentState ports.ServiceCurrentState, err error) *MockServiceAnalyticsStore_GetServiceCurrentState_Call {
	_c.Call.Return(serviceCurrentState, err)
	return _c
}

func (_c *MockServiceAnalyticsStore_GetServiceCurrentState_Call) RunAndReturn(run func(ctx context.Context, organizationID int64, service string) (ports.ServiceCurrentState, error)) *MockServiceAnalyticsStore_GetServiceCurrentState_Call {
	_c.Call.Return(run)
	return _c
}

// GetServiceDeliveryStats30d provides a mock function for the type MockServiceAnalyticsStore
func (_mock *MockServiceAnalyticsStore) GetServiceDeliveryStats30d(ctx context.Context, organizationID int64, service string) (ports.ServiceDeliveryStats, error) {
	ret := _mock.Called(ctx, organizationID, service)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceDeliveryStats30d")
	}

	var r0 ports.ServiceDeliveryStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (ports.ServiceDeliveryStats, error)); ok {
		return returnFunc(ctx, organizationID, service)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) ports.ServiceDeliveryStats); ok {
		r0 = returnFunc(ctx, organizationID, service)
	} else {
		r0 = ret.Get(0).(ports.ServiceDeliveryStats)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, organizationID, service)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceAnalyticsStore_GetServiceDeliveryStats30d_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceDeliveryStats30d'
type MockServiceAnalyticsStore_GetServiceDeliveryStats30d_Call struct {
	*mock.Call
}

// GetServiceDeliveryStats30d is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
//   - service string
func (_e *MockServiceAnalyticsStore_Expecter) GetServiceDeliveryStats30d(ctx interface{}, organizationID interface{}, service interface{}) *MockServiceAnalyticsStore_GetServiceDeliveryStats30d_Call {
	return &MockServiceAnalyticsStore_GetServiceDeliveryStats30d_Call{Call: _e.mock.On("GetServiceDeliveryStats30d", ctx, organizationID, service)}
}

func (_c *MockServiceAnalyticsStore_GetServiceDeliveryStats30d_Call) Run(run func(ctx context.Context, organizationID int64, service string)) *MockServiceAnalyticsStore_GetServiceDeliveryStats30d_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServiceAnalyticsStore_GetServiceDeliveryStats30d_Call) Return(serviceDeliveryStats ports.ServiceDeliveryStats, err error) *MockServiceAnalyticsStore_GetServiceDeliveryStats30d_Call {
	_c.Call.Return(serviceDeliveryStats, err)
	return _c
}

func (_c *MockServiceAnalyticsStore_GetServiceDeliveryStats30d_Call) RunAndReturn(run func(ctx context.Context, organizationID int64, service string) (ports.ServiceDeliveryStats, error)) *MockServiceAnalyticsStore_GetServiceDeliveryStats30d_Call {
	_c.Call.Return(run)
	return _c
}

// ListServiceChangeLinksRecent provides a mock function for the type MockServiceAnalyticsStore
func (_mock *MockServiceAnalyticsStore) ListServiceChangeLinksRecent(ctx context.Context, organizationID int64, service string, limit int64) ([]ports.ServiceChangeLink, error) {
	ret := _mock.Called(ctx, organizationID, service, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListServiceChangeLinksRecent")
	}

	var r0 []ports.ServiceChangeLink
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, int64) ([]ports.ServiceChangeLink, error)); ok {
		return returnFunc(ctx, organizationID, service, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, int64) []ports.ServiceChangeLink); ok {
		r0 = returnFunc(ctx, organizationID, service, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.ServiceChangeLink)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, int64) error); ok {
		r1 = returnFunc(ctx, organizationID, service, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceAnalyticsStore_ListServiceChangeLinksRecent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServiceChangeLinksRecent'
type MockServiceAnalyticsStore_ListServiceChangeLinksRecent_Call struct {
	*mock.Call
}

// ListServiceChangeLinksRecent is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationID int64
//   - service string
//   - limit int64
func (_e *MockServiceAnalyticsStore_Expecter) ListServiceChangeLinksRecent(ctx interface{}, organizationID interface{}, service interface{}, limit interface{}) *MockServiceAnalyticsStore_ListServiceChangeLinksRecent_Call {
	return &MockServiceAnalyticsStore_ListServiceChangeLinksRecent_Call{Call: _e.mock.On("ListServiceChangeLinksRecent", ctx, organizationID, service, limit)}
}

func (_c *MockServiceAnalyticsStore_ListServiceChangeLinksRecent_Call) Run(run func(ctx context.Context, organizationID int64, service string, limit int64)) *MockServiceAnalyticsStore_ListServiceChangeLinksRecent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockServiceAnalyticsStore_ListServiceChangeLinksRecent_Call) Return(serviceChangeLinks []ports.ServiceChangeLink, err error) *MockServiceAnalyticsStore_ListServiceChangeLinksRecent_Call {
	_c.Call.Return(serviceChangeLinks, err)
	return _c
}

func (_c *MockServiceAnalyticsStore_ListServiceChangeLinksRecent_Call) RunAndReturn(run func(ctx context.Context, organizationID int64, service string, limit int64) ([]ports.ServiceChangeLink, error)) *MockServiceAnalyticsStore_ListServiceChangeLinksRecent_Call {
	_c.Call.Return(run)
	return _c
}
